### ISSUE TITLE
TypeError: string.endsWith is not a function

### ISSUE THREAD

**Issue by svsool** [jest-community/jest-extended#291]
**Bug**

- `package` version: 0.11.5
- `node` version: v14.4.0
- `yarn` version: 1.22.4

Relevant code or config

```javascript
it('should detect position properly for the first reference', async () => {
    const name = rndName();

    await createFile(
      `${name}.md`,
      '[[README|Start here]] or refer to any other [[Note]]. Use (cmd or ctrl) + click on the [[Note]] to create a new note to the disk on the fly.',
    );

    const refs = await findReferences('README');

    expect(refs).toHaveLength(1);

    expect(toPlainObject(refs)).toMatchObject([
      {
        location: {
          uri: {
            $mid: 1,
            path: expect.toEndWith(`${name}.md`),
            scheme: 'file',
          },
          range: [
            { line: 0, character: 2 },
            { line: 0, character: 6 },
          ],
        },
        matchText: '[[README]]',
      },
    ]);
  });
```

What you did:

Ran that test and it failed.

What happened (please provide anything you think will help):

I added console.log to `node_modules/jest-extended/dist/matchers/toEndWith/predicate.js` and this is the output:

```

  console.log
    suffix ifrhe.md string /var/folders/k8/6v4kb71x59x87fcsr7_vhhnm0000gn/T/memo-pZUmdW/ifrhe.md

      at exports.default (node_modules/jest-extended/dist/matchers/toEndWith/predicate.js:8:11)
          at Array.every (<anonymous>)
          at Array.every (<anonymous>)
          at Array.every (<anonymous>)

  console.log
    suffix ifrhe.md string /var/folders/k8/6v4kb71x59x87fcsr7_vhhnm0000gn/T/memo-pZUmdW/ifrhe.md

      at exports.default (node_modules/jest-extended/dist/matchers/toEndWith/predicate.js:8:11)
          at Array.every (<anonymous>)
          at Array.every (<anonymous>)
          at Array.every (<anonymous>)
          at Array.map (<anonymous>)

  console.log
    suffix ifrhe.md string /var/folders/k8/6v4kb71x59x87fcsr7_vhhnm0000gn/T/memo-pZUmdW/ifrhe.md

      at exports.default (node_modules/jest-extended/dist/matchers/toEndWith/predicate.js:8:11)
          at Array.every (<anonymous>)
          at Array.every (<anonymous>)
          at Array.forEach (<anonymous>)
          at Array.map (<anonymous>)

  console.log
    suffix ifrhe.md string /var/folders/k8/6v4kb71x59x87fcsr7_vhhnm0000gn/T/memo-pZUmdW/ifrhe.md

      at exports.default (node_modules/jest-extended/dist/matchers/toEndWith/predicate.js:8:11)
          at Array.every (<anonymous>)
          at Array.forEach (<anonymous>)
          at Array.forEach (<anonymous>)
          at Array.map (<anonymous>)

  console.log
    suffix ifrhe.md string CustomMatcher {
      sample: [ 'ifrhe.md' ],
      '$$typeof': Symbol(jest.asymmetricMatcher),
      inverse: false
    }

      at exports.default (node_modules/jest-extended/dist/matchers/toEndWith/predicate.js:8:11)
          at Array.forEach (<anonymous>)
          at Array.forEach (<anonymous>)
          at Array.forEach (<anonymous>)
          at Array.forEach (<anonymous>)
```

I can see the last call receives object instead of a string for some reason.

This error disappears as soon as other problems with the test are fixed, for instance `ref.range` and `matchText` are correct, otherwise it swallows other errors and gives this weird `TypeError: string.endsWith is not a function`.

Please let me know if I don't use this matcher as expected. 

For a note `expect.stringContaining` matcher works.

**Comment by Imran99** [comment]
Did you ever get to the bottom of this, I see something similar when I have a failing test asserting an array, in my case I see `TypeError: result.message is not a function`. This appears to only happen when using jest extended matchers.

**Comment by Imran99** [comment]
For me it ended up being an issue with jest-chain https://github.com/mattphillips/jest-chain/issues/22
