### ISSUE TITLE
Add back support for node 16.10

### ISSUE THREAD

**Issue by ParallelUniv3rse** [jest-community/jest-extended#476]
**Feature Request**

Description:
Please add back support for node 16.10 into the `package.json` `engines` field. 
the latest versions of jest-extended cannot be used when you're trying to avoid high memory consumption by jest in node v 16.11+ as described in https://github.com/facebook/jest/issues/11956. 

This concerns jest-extended `^2.1.0` as well as `^3.0.0`. 

Possible solution:
Lower engines requirements for node to `16.10` from `16.13` in `package.json`

**Comment by ParallelUniv3rse** [comment]
Thank you for considering and for the explanation. Not sure about npm, but yarn fails to install on the engines requirement. 

For anyone using yarn and looking for a workaround: 
`yarn install --ignore-engines`

**Comment by SimenB** [comment]
I think we can do the same here as in https://github.com/facebook/jest/pull/12754 just so people don't have to supply a flag (or ignore warnings)

**Comment by keeganwitt** [comment]
I don't object. I don't pay much attention to `engines` warnings personally.

**Comment by ShruthiNicheSolv** [comment]
I have node `16.13.1` with `jest` "^29.5.0" but getting
```
> jest --coverage

/home/shruthi/Projects/test/node_modules/jest-cli/build/run.js:129
    if (error?.stack) {
              ^

SyntaxError: Unexpected token .
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/shruthi/Projects/test/node_modules/jest-cli/build/index.js:18:12)
```
